// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LifeSong","status":true,"description":"《余音》核心插件：旋律小游戏、章节标题卡、对话名字框、像素字体与菜单美化。","parameters":{"Font Size":"24","Text Wait":"1","Chapter Variable":"1","Fragment Variable":"2","Fragment Max":"5"}}
];
