"""The cast of 《余音》 — every character sheet the game uses."""
from chars import Spec
import palette as P

BLACK_HAIR = '#3a2c2e'
BROWN_HAIR = '#6b4630'
GREY_HAIR = '#b9b4ad'
WHITE_HAIR = '#ece8e0'
SKIN_OLD = '#efcfb0'

CAST = {
    # ---- 林音 through her life -------------------------------------------
    '$Yin_Child': Spec(body='child', hair=BLACK_HAIR, hair_style='twintails', fringe='full',
                       top='#d8574f', top2='#fbf8f2', legwear='dress', shoes='#c0392b',
                       acc_col={'tie': '#f7d55c'}),
    '$Yin_Teen': Spec(body='adult', hair=BLACK_HAIR, hair_style='ponytail', fringe='side',
                      top='#f4f2ea', top2='#3f6fb0', bottom='#3f6fb0', legwear='pants', shoes=P.WHITE,
                      acc=['stripe'], acc_col={'stripe': '#3f6fb0', 'tie': '#d8574f'}),
    '$Yin_Adult': Spec(body='adult', hair=BLACK_HAIR, hair_style='long', fringe='side',
                       top='#e9e4da', coat='#c9a070', bottom='#3f5a8a', legwear='pants', shoes='#5a3a2a',
                       acc=['scarf', 'guitar'], acc_col={'scarf': '#d8302a', 'guitar': '#2e2a36'}),
    '$Yin_Middle': Spec(body='adult', hair='#4a3a36', hair_style='bob', fringe='side',
                        top='#6a9a7a', top2='#5a8a6a', bottom='#8a6a5a', legwear='longskirt', shoes='#5a3a2a',
                        acc=['grey_streak']),
    '$Yin_Old': Spec(body='old', skin=SKIN_OLD, hair=WHITE_HAIR, hair_style='bun', fringe='none',
                     top='#7a6a8a', bottom='#5a4a6a', legwear='longskirt', shoes='#3a3540',
                     acc=['glasses', 'shawl', 'hairpin'], acc_col={'shawl': '#b57aa8', 'hairpin': '#d8302a',
                                                                   'glasses': '#8a6a3a'}, blush=False),
    # ---- family & friends ---------------------------------------------------
    '$Grandpa': Spec(body='old', skin=SKIN_OLD, hair=WHITE_HAIR, hair_style='bald', fringe='none',
                     top='#5f7186', top2='#5f7186', bottom='#3a3540', legwear='pants', shoes='#2a2630',
                     acc=['beard'], blush=False),
    '$Mom': Spec(body='adult', hair=BLACK_HAIR, hair_style='bob', fringe='parted',
                 top='#e8a0a0', bottom='#5a5a6a', legwear='pants', shoes='#5a3a2a',
                 acc=['apron'], acc_col={'apron': '#f4f0e6'}, blush=False),
    '$Jie_Teen': Spec(body='adult', hair=BROWN_HAIR, hair_style='short', fringe='spiky',
                      top='#f4f2ea', top2='#3f6fb0', bottom='#3f6fb0', shoes=P.WHITE,
                      acc=['stripe'], acc_col={'stripe': '#3f6fb0'}, blush=False),
    '$Jie_Adult': Spec(body='adult', hair=BROWN_HAIR, hair_style='short', fringe='side',
                       top='#f4f2ea', coat='#3d4a66', bottom='#2e3448', shoes='#2a2630',
                       acc=['tie', 'bag'], acc_col={'tie_col': '#8a3a3a', 'bag': '#5a4030'}, blush=False),
    '$Jie_Old': Spec(body='old', skin=SKIN_OLD, hair=WHITE_HAIR, hair_style='short', fringe='side',
                     top='#a87a5a', bottom='#4a4a5a', shoes='#3a3540',
                     acc=['glasses', 'guitar'], acc_col={'guitar': '#7a4a2a'}, blush=False),
    '$Teacher_Wang': Spec(body='adult', hair=BLACK_HAIR, hair_style='short', fringe='parted',
                          top='#e8e4dc', coat='#8a7a5a', bottom='#4a4a5a', shoes='#3a3540',
                          acc=['glasses'], blush=False),
    '$Xiaoyu_Child': Spec(body='child', hair=BROWN_HAIR, hair_style='bob', fringe='full',
                          top='#f2a0b8', coat='#f2a0b8', bottom='#f2a0b8', legwear='pants', shoes='#8a3a4a',
                          acc=['knit_hat', 'scarf'], acc_col={'knit_hat': '#d8302a', 'scarf': P.WHITE}),
    '$Xiaoyu_Mom': Spec(body='adult', hair=BROWN_HAIR, hair_style='ponytail', fringe='side',
                        top='#9a9aa4', coat='#7a7a86', bottom='#3a3a46', shoes='#2a2630',
                        acc_col={'tie': '#3a3540'}, blush=False),
    '$Xiaoyu_Adult': Spec(body='adult', hair='#8a7a6a', hair_style='bob', fringe='side',
                          top='#e8e4dc', coat='#5a7a9a', bottom='#3a3a46', shoes='#2a2630',
                          acc=['glasses', 'scarf'], acc_col={'scarf': '#f2a0b8'}, blush=False),
    '$Xiaohe_Child': Spec(body='child', hair=BLACK_HAIR, hair_style='bob', fringe='full',
                          top='#f7d55c', top2='#f7d55c', bottom='#3f6fb0', legwear='pants', shoes='#c0392b',
                          acc=['hairclip'], acc_col={'hairclip': '#d8302a'}),
    '$Xiaohe_Adult': Spec(body='adult', hair=BLACK_HAIR, hair_style='ponytail', fringe='side',
                          top='#fbf8f2', bottom='#2e3f6b', legwear='skirt', shoes='#2a2630',
                          acc_col={'tie': '#f7d55c'}, blush=False),
    '$Duoduo': Spec(body='child', hair=BROWN_HAIR, hair_style='twintails', fringe='full',
                    top='#f08a3a', top2='#fbf8f2', legwear='dress', shoes='#8a3a2a',
                    acc_col={'tie': '#5aa0d8'}),
    # ---- villagers / townsfolk ----------------------------------------------
    '$Granny_Li': Spec(body='old', skin=SKIN_OLD, hair=GREY_HAIR, hair_style='bun', fringe='none',
                       top='#7fa8c8', bottom='#3a3a46', legwear='pants', shoes='#2a2630', blush=False),
    '$Fisherman': Spec(body='adult', skin='#e8b88f', hair=BLACK_HAIR, hair_style='short', fringe='full',
                       top='#f4f2ea', bottom='#5a6a7a', legwear='pants', shoes='#5a3a2a',
                       acc=['straw_hat'], blush=False),
    '$Kid_Boy': Spec(body='child', skin='#efc29a', hair=BLACK_HAIR, hair_style='short', fringe='spiky',
                     top='#5a9a5a', bottom='#3a3a46', shoes='#2a2630'),
    '$Kid_Girl': Spec(body='child', hair=BROWN_HAIR, hair_style='buns', fringe='full',
                      top='#a98ee0', legwear='dress', shoes='#5a3a6a'),
    '$Vendor': Spec(body='adult', skin='#e8b88f', hair=BLACK_HAIR, hair_style='short', fringe='full',
                    top='#fbf8f2', bottom='#5a5a6a', shoes='#3a3540', acc=['cap'],
                    acc_col={'cap': '#d8302a'}, blush=False),
    '$Cafe_Owner': Spec(body='adult', hair=BLACK_HAIR, hair_style='bun', fringe='side',
                        top='#e8e4dc', bottom='#3a3540', shoes='#3a3540', acc=['apron'],
                        acc_col={'apron': '#8a5a3a'}, blush=False),
    '$Receptionist': Spec(body='adult', hair=BROWN_HAIR, hair_style='bob', fringe='full',
                          top='#fbf8f2', coat='#2e3448', bottom='#2e3448', legwear='skirt', shoes='#2a2630',
                          blush=False),
    '$Passerby_Suit': Spec(body='adult', hair=BLACK_HAIR, hair_style='short', fringe='parted',
                           top='#e8e4dc', coat='#4a4a56', bottom='#3a3a46', shoes='#2a2630',
                           acc=['bag'], acc_col={'bag': '#2a2630'}, blush=False),
    '$Passerby_Student': Spec(body='adult', hair=BROWN_HAIR, hair_style='short', fringe='full',
                              top='#5a9ad0', coat='#d8a04a', bottom='#3a4a6a', shoes=P.WHITE,
                              acc=['headphones'], blush=False),
    '$Passerby_Woman': Spec(body='adult', hair='#7a4a3a', hair_style='long', fringe='side',
                            top='#e8e4dc', coat='#b8584a', bottom='#3a3a46', shoes='#3a3540',
                            acc=['bag'], acc_col={'bag': '#c9a070'}, blush=False),
    '$Student_A': Spec(body='adult', hair=BLACK_HAIR, hair_style='bob', fringe='full',
                       top='#f4f2ea', top2='#3f6fb0', bottom='#3f6fb0', shoes=P.WHITE,
                       acc=['stripe'], acc_col={'stripe': '#3f6fb0'}),
    '$Student_B': Spec(body='adult', hair=BLACK_HAIR, hair_style='short', fringe='full',
                       top='#f4f2ea', top2='#3f6fb0', bottom='#3f6fb0', shoes=P.WHITE,
                       acc=['stripe', 'glasses'], acc_col={'stripe': '#3f6fb0'}, blush=False),
    '$Student_C': Spec(body='adult', hair=BROWN_HAIR, hair_style='twintails', fringe='side',
                       top='#f4f2ea', top2='#3f6fb0', bottom='#3f6fb0', shoes=P.WHITE,
                       acc=['stripe'], acc_col={'stripe': '#3f6fb0', 'tie': '#3f6fb0'}),
    '$Farmer': Spec(body='old', skin='#e8b88f', hair=GREY_HAIR, hair_style='short', fringe='full',
                    top='#8a9a6a', bottom='#4a4a3a', shoes='#3a3540', acc=['straw_hat'], blush=False),
    '$Villager_Woman': Spec(body='adult', hair=BLACK_HAIR, hair_style='ponytail', fringe='parted',
                            top='#c46a6a', bottom='#3a3a46', legwear='pants', shoes='#3a3540', blush=False),
    '$Doctor': Spec(body='adult', hair=BLACK_HAIR, hair_style='short', fringe='side',
                    top='#e8f0f4', coat='#f4f8fa', bottom='#5a6a7a', shoes='#3a3540',
                    acc=['glasses'], blush=False),
}
